name: Deploy Content to gdapwcuswokspace02 [8f2f474f-d6b2-4b37-af94-708b18bcaecc]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-8f2f474f-d6b2-4b37-af94-708b18bcaecc.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main-sentinel-deployment-sentinel-deployment-sentinel-deployment ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-8f2f474f-d6b2-4b37-af94-708b18bcaecc.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'sentinelcanary'
      workspaceName: 'gdapwcuswokspace02'
      workspaceId: '3cac4bc2-027c-4166-b17d-7d51e4c712af'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'Parser'
      branch: 'main-sentinel-deployment-sentinel-deployment-sentinel-deployment'
      sourceControlId: '8f2f474f-d6b2-4b37-af94-708b18bcaecc'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_8f2f474fd6b24b37af94708b18bcaecc }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_8f2f474fd6b24b37af94708b18bcaecc }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_8f2f474fd6b24b37af94708b18bcaecc }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_8f2f474fd6b24b37af94708b18bcaecc }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_8f2f474fd6b24b37af94708b18bcaecc }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_8f2f474fd6b24b37af94708b18bcaecc }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_8f2f474fd6b24b37af94708b18bcaecc }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_8f2f474fd6b24b37af94708b18bcaecc }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_8f2f474fd6b24b37af94708b18bcaecc }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-8f2f474f-d6b2-4b37-af94-708b18bcaecc.ps1