name: Deploy Content to SentinelWorkspace2 [e95b482f-db00-441e-8f52-62199e7c6257]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-e95b482f-db00-441e-8f52-62199e7c6257.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main-sentinel-deployment ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-e95b482f-db00-441e-8f52-62199e7c6257.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'SentinelRG'
      workspaceName: 'SentinelWorkspace2'
      workspaceId: '507ad8b3-478b-40d1-91b2-0edcb1f0575f'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'Workbook'
      branch: 'main-sentinel-deployment'
      sourceControlId: 'e95b482f-db00-441e-8f52-62199e7c6257'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_e95b482fdb00441e8f5262199e7c6257 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_e95b482fdb00441e8f5262199e7c6257 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_e95b482fdb00441e8f5262199e7c6257 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_e95b482fdb00441e8f5262199e7c6257 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_e95b482fdb00441e8f5262199e7c6257 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_e95b482fdb00441e8f5262199e7c6257 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_e95b482fdb00441e8f5262199e7c6257 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_e95b482fdb00441e8f5262199e7c6257 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_e95b482fdb00441e8f5262199e7c6257 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-e95b482f-db00-441e-8f52-62199e7c6257.ps1